"""
Confusion Matrix Visualization for GAN Predictions
--------------------------------------------------
This script computes the confusion matrix for predictions generated by 
the GAN-based discriminator and visualizes it using matplotlib. 
It helps to assess classification performance by showing true vs. predicted labels.

GAN 예측 혼동 행렬 시각화
--------------------------------------------------
이 스크립트는 GAN 기반 판별기의 예측 결과에 대한 혼동 행렬을 계산하고 
matplotlib을 이용해 시각화합니다. 
실제 라벨과 예측 라벨을 비교하여 분류 성능을 평가하는 데 유용합니다.
"""

cm = confusion_matrix(y_test, y_pred)

print ('Confusion Matrix :')

def plot_confusion_matrix(cm, title='Confusion matrix', cmap=plt.cm.Greens):
    plt.figure(figsize=(10,10),)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    plt.tight_layout()

    width, height = cm.shape

    for x in range(width):
        for y in range(height):
            plt.annotate(str(cm[x][y]), xy=(y, x), 
                        horizontalalignment='center',
                        verticalalignment='center')
    plt.ylabel('True label')
    plt.xlabel('Predicted label')


plot_confusion_matrix(cm)
