"""
ROC Curve Visualization for GAN Predictions
-------------------------------------------
This script computes and plots the Receiver Operating Characteristic (ROC) curve 
for predictions generated by the GAN-based discriminator. It also calculates 
the Area Under the Curve (AUC) to summarize classification performance.

GAN 예측 ROC 곡선 시각화
-------------------------------------------
이 스크립트는 GAN 기반 판별기의 예측 결과에 대해 
수신자 조작 특성(ROC) 곡선을 계산하고 시각화합니다. 
또한 AUC(곡선 아래 면적)를 계산하여 분류 성능을 요약합니다.
"""

fpr_keras, tpr_keras, thresholds_keras = roc_curve(y_test, y_pred)
auc_keras = auc(fpr_keras, tpr_keras)
plt.figure(1)
plt.plot([0, 1], [0, 1], 'k--')
plt.plot(fpr_keras, tpr_keras, label='Keras (area = {:.2f})'.format(auc_keras))

plt.xlabel('False positive rate')
plt.ylabel('True positive rate')
plt.title('ROC curve')
plt.legend(loc='best')
plt.show()
